resources:
  repositories:
  - repository: iacRepo
    type: git
    name: 'AZ-400 eWebShop/IaC Repo'

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: iacRepo
- script: ls ./bicep